### ISSUE TITLE
OpenData_Slovakia_Covid_Deaths_AgeGroup_District.xlsx chyba #value

### ISSUE THREAD

**Issue by mrakoplas-sk** [Institut-Zdravotnych-Analyz/covid19-data#100]
Zdravim,
v najnovsej verzii z  1.6.2021 je chyba #value na riadku 8537. Moze to rozhodit ludomdata ak pouzivaju PowerQuery na zobrazenie dat.
Pocty zomretych vobec nekoresponduju so skutocnymi zomretymi. Tieto data podla veku a pohlavia sa uz nebudu zistovat?
Diky

**Comment by matejmisik** [comment]
Dobry den, spravili sme update umrti (detailu aj dennych hlaseni), uz by tam nemala byt chyba. Ospravedlnujem sa.

**Comment by mrakoplas-sk** [comment]
sorry, ale pocty podla mesiacov nesedia, pravdepodobne uz presne nbebudeme poznat.
marec - 2520 - vase data 2427
april - 1943 - vase data 1007
maj - 621 - vase data 219
