### ISSUE TITLE
stop Update data from 09. 06. 2021

### ISSUE THREAD

**Issue by JRHumor** [Institut-Zdravotnych-Analyz/covid19-data#102]
From 09. 06. 2021 is updated only "cakaren"

**Comment by kajbo92** [comment]
1,5 years and still cant get daily updated stats on time ...

**Comment by KristianSufliarsky** [comment]
Hey, 
I have to apologize, for this, but since porvier of this data changed the structure without notifying us. I was told it will be fixed today. 
Kristian

**Comment by mhudec** [comment]
Vaccination data (covid19-data/Vaccination/OpenData_Slovakia_Vaccination_Regions.csv) have been updated. Antigen test data (covid19-data/AG_Tests/OpenData_Slovakia_Covid_AgTests_District.*) are pending...

**Comment by mhudec** [comment]
Antigen test data (covid19-data/AG_Tests/OpenData_Slovakia_Covid_AgTests_District.*) have been partially updated, thank you... there are discrepancies however, e.g. missing April data... well, maybe tomorrow.
