### ISSUE TITLE
Spikevax v Košickom kraji

### ISSUE THREAD

**Issue by lukaskogaborik** [Institut-Zdravotnych-Analyz/covid19-data#106]
Podľa dát v OpenData_Slovakia_Vaccination_Regions.csv bolo v Košickom kraji podaných 14 566 prvých dávok a 15 252 druhých dávok vakcíny Spikevax, teda viac druhých dávok ako dávok prvých. Ide o chybu v dátach, či pod to spadajú ľudia, ktorí prvú dávku Spikevax dostali mimo Košického kraja a druhú už v ňom?

**Comment by matejmisik** [comment]
Dobry den, ano - ak davky su vedene tam kde boli podane, cize moze byt ze
prva davka je vedena v zilinskom, druha v kosickom.
M--
