### ISSUE TITLE
Hospitalizovaný neočkovaní - očkovaní

### ISSUE THREAD

**Issue by ondrejHencz** [Institut-Zdravotnych-Analyz/covid19-data#112]
Dobrý deň
Kedy sa začnú zdieľať dáta o hospitalizovaných ktorí budú delení na očkovaní/neočkovaní?
Ďakujem

**Comment by MartinHBA** [comment]
uz je to tam, asi mozeme zavriet

**Comment by ondrejHencz** [comment]
Dobrý deň
Viete mi prosím poradiť správne pochopiť dáta? Napr.:
"546";2021-08-13;FALSE;5;0
"547";2021-08-13;TRUE;1;0
"548";2021-08-13;NA;2;6
False znamená, že sú neočkovaný (5 prijatých, 0 prepustených), True ako očkovaný (1 prijatý, 0 prepustených), a čo znamena NA (2 prijatý, 6 prepustených)? To sú pacienti ktorý to neuvádzajú, NCZi nevie či sú alebo nie, alebo ako chápať tento údaj?

Potom by som sa chcel ešte spýytať, či by sa očkovanosť dala uvádzať aj pre úmrtia, ale aj pre testovaných?
Ďakujem

**Comment by MartinHBA** [comment]
ja to chapem takto: True : plne ockovani, False : zvysok, N/A : nemame informacie o zaockovanosti prijateho pacienta

**Comment by ondrejHencz** [comment]
Ďakujem za odpoveď, 
na druhú otázku mám otvoriť novú tému?
**Potom by som sa chcel ešte spýytať, či by sa očkovanosť dala uvádzať aj pre úmrtia, ale aj pre testovaných?**
Ďakujem

**Comment by MartinHBA** [comment]
odporucil by som toto zavriet a na umrtia otvorit novu
