### ISSUE TITLE
OpenData_Slovakia_Covid_PCRTests_District.csv

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#113]
chybaju data od 1.7. do 6.7.2021

**Comment by b-mi** [comment]
Je 9. 10, posledne data su z 3. 10. To tam nikto nevklada data a preto sa nedaju nejakym cyklickym taskom automatizovane generovat?

**Comment by MartinHBA** [comment]
old issue
