### ISSUE TITLE
OpenData_Slovakia_Vaccination_AgeGroup_District.csv

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#116]
stlpec dose obsahuje 1% udajov ako "fully" namiesto 1 a 2, vcera tam bol novy stlpec doobedu vacc status, ten vecer zmizol ale zanechal chyby... och...

**Comment by matejmisik** [comment]
Zdravim Martin, ospravedlnujeme sa, spekulovali sme ako to spravit (sorry, ze na produkcii). Kazdopadne sme to nakoniec spravili s co najmensim impact na logiku, pribudol k poctu doses este treti stav "fully", ktory sa pocit presne podla vyhlasky (aj s poctom dni po ockovani) a teda odzrkadluje aj co najlepsie realnu proporciu obyvatelstva plne chranenych vakcinou.
