### ISSUE TITLE
OpenData_Slovakia_Covid_AgTests_District.csv file encoding

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#12]
Neviem to zatial so ziadnym encoding nacitat s diakritikou. Co je to prosim za encoding?
inak tento subor ma rozdelene okresy KE a BA, a co mate dataset pre PCR : OpenData_Slovakia_Covid_PositiveTests_AgeGroup_District.csv
tak tam mate KE a BA ako jeden okres. Ako da sa to ucesanim post process dat dokopy.

**Comment by matejmisik** [comment]
Dam to sem este ako excel, no idea preco nejde diakritika, je to rovnaky export z excel ako vzdy do csv. 
Co sa BA a KE tyka - pri Ag to dostavam na nizsej granularite, tak to radsej poskytneme takto. Pri PCR to dostavame iba na urovni BA / KE.

**Comment by sk-juroot** [comment]
Ten `OpenData_Slovakia_Covid_AgTests_District.csv` je v kódovaní Windows-1250

Jedna z vecí, ktoré Excel naozaj nezvláda, je export do csv s korektným zápisom kódovania. Defaultne prispôsobuje kódovanie tomu, aký je jazyk systému a balíka Office. Väčšinou pomôže hneď po exporte a zatvorení Excelu (inak drží handle súboru) otvoriť ho v nejakom pokročilejšom textovom editore, ktorý deteguje kódovanie z textu a uložiť ako UTF-8.
