### ISSUE TITLE
Deaths data 3 mesiace stare?

### ISSUE THREAD

**Issue by globalistas** [Institut-Zdravotnych-Analyz/covid19-data#121]
Preco ste prestali updatovat tieto subory?

https://github.com/Institut-Zdravotnych-Analyz/covid19-data/tree/main/Deaths

**Comment by MartinHBA** [comment]
toto sa dlhodobo updatuje tak raz za 2, 3 mesiace...

**Comment by globalistas** [comment]
> toto sa dlhodobo updatuje tak raz za 2, 3 mesiace...

Dlhodobo? Do Juna sa to updatovalo 2x do mesiaca, a od Juna ani jeden novy update:

https://github.com/Institut-Zdravotnych-Analyz/covid19-data/commits/main/Deaths/OpenData_Slovakia_Covid_Deaths_AgeGroup_District.xlsx

**Comment by BInLabVIEW** [comment]
Update tohto by bol fakt pekny - stale niekto operuje na socialnych mediach v analyzach s tym, ake mame cisla umrti, ale sudiac podla minuleho roku reportovane ozaj meskaju - s tymto datovym suborom sa da aspon hadat, ake su aktualne. Na jar sme mali chvilami underreporting v danom case na urovni 1500 mrtvych (alebo 2+ tyzdne v casovej skale) co vidiet az pri pohlade na tieto data

**Comment by BInLabVIEW** [comment]
dakujeme za update

**Comment by MartinHBA** [comment]
@globalistas , zavries si to? asi sa na tom uz nic nezmeni
