### ISSUE TITLE
dataset o vakcináciách neobsahuje rok

### ISSUE THREAD

**Issue by MichalPP** [Institut-Zdravotnych-Analyz/covid19-data#137]
[dataset o vakcinácíach](https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/main/Vaccination/OpenData_Slovakia_Vaccination_AgeGroup_District_comma.csv) podľa okresov neobsahuje rok, teda v roku 2022 zblbne. asi treba doplniť stĺpec "rok"

plus počet vakcinovaných ľudí nesedí s inými zdrojmi. v tomto datasete je 2481358, korona.gov.sk hovorí 2 668 033 (rozdiel vyše 200 000 ľudí čo nemôžu byť chýbajúce dáta za posledný deň-dva). 

vďaka

**Comment by MichalPP** [comment]
či číslo týždňa 53 znamená týždeň 1 roku 2022?

**Comment by uhliksk** [comment]
Už je tam doplnený ISO formát (iso_week, iso_year), len asi zabudli označiť issue ako vyriešený.

**Comment by MartinHBA** [comment]
@MichalPP , mozes to asi zavriet aj ty, asi nemaju cas chalani
