### ISSUE TITLE
Chýbajúce dáta na čakáreň pre tretiu dávku 

### ISSUE THREAD

**Issue by Mincoslav** [Institut-Zdravotnych-Analyz/covid19-data#142]
Najnovšie [údaje](https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/8bf5f8cfe7904837b72af19eed4c3043b55b30fa/Vaccination/OpenData_Slovakia_Vaccination_Cakaren.csv) (20.12.2021) pre čakáreň neobsahujú údaje pre tretie dávky (boostery)
Budú tieto údaje doplnené? 
Ďakujem.

**Comment by MartinHBA** [comment]
@Mincoslav , zavries si to sam alebo este pockame? 💤

**Comment by matejmisik** [comment]
Tieto data sme ani nedostavali, ani sme o ne aktivne nebojovali, nakolko v case boostrov uz tolko ludi chodilo walk-in + existovalo tolko vlastnych cakarni, ze by to bol nic nehovoriaci udaj. Optimalzujeme, ze co stoji za to, aby sme si zas pohnevali nczi ;)
