### ISSUE TITLE
Duplicity Ag testovania

### ISSUE THREAD

**Issue by sk-juroot** [Institut-Zdravotnych-Analyz/covid19-data#15]
Na základe [medializovaných informácií](https://domov.sme.sk/c/22550932/nemocnice-vykazali-o-desattisice-antigenovych-testov-viac-ako-urobili.html) boli v bližšie nešpecifikovaných dátumoch duplicitne hlásené vykonané a pozitívne antigénové testy. Otváram preto issue, keďže predpokladám, že sa tieto nesprávne údaje dostali aj do týchto otvorených dát, ktoré nie je možné vzhľadom na štruktúru očistiť bez zásahu zodpovednej inštitúcie.

**Comment by matejmisik** [comment]
Asi uz nie uplne relevant odpoved, ale prechadzam to tu tak doplnim: velka vacsina dat co sem ide (okrem daily PCR case counts s vekom) ako full load. Cize ked nieco u seba upravi NCZI tak sa to dostane aj sem.
