### ISSUE TITLE
PCR_Tests

### ISSUE THREAD

**Issue by Elkabeielika** [Institut-Zdravotnych-Analyz/covid19-data#152]
### Discussed in https://github.com/Institut-Zdravotnych-Analyz/covid19-data/discussions/147

<div type='discussions-op-text'>

<sup>Originally posted by **Elkabeielika** January  7, 2022</sup>
Sú dostupné údaje datasetu OpenData_Slovakia_Covid_PCRTests_AgeGroup_District.csv od 06.03.2020 do 01.05.2021?</div>

**Comment by matejmisik** [comment]
Zial nie. Neexistoval vtedy este ten source system u NCZI. Pokusime sa ale spracovat UVZ aby poskytli export z EPIS, kde maju kazdy jeden spracovany pripad od zaciatku pandemie bez ohladu na typ testu.
