### ISSUE TITLE
AG_Tests, Ambulance, DailyStats, Deaths sa prestali aktualizovat

### ISSUE THREAD

**Issue by diavollo** [Institut-Zdravotnych-Analyz/covid19-data#153]
AG_Tests, Ambulance, DailyStats, Deaths sa prestali aktualizovat. chybicka, alebo umysel?

**Comment by matejmisik** [comment]
Chybicka, dakujeme za upozornenie. Obcas nam pod rukou bez predosleho info zmenia struktury podkladovych dat. V blizkej dobe sa ale znizi frekvencia aktualizacii, nakolko aj nam budu zriedkavejsie prudit podkladove data.
