### ISSUE TITLE
vaccination data not updated since Friday 19th August

### ISSUE THREAD

**Issue by mhudec** [Institut-Zdravotnych-Analyz/covid19-data#160]
There are no updates for vaccination data since Friday 19th August 2022... would you mind looking in to it, please? Thanks.

Vaccination/OpenData_Slovakia_Vaccination_AgeGroup_District.csv
Vaccination/OpenData_Slovakia_Vaccination_AgeGroup_District_comma.csv
Vaccination/OpenData_Slovakia_Vaccination_Regions.csv

**Comment by matejmisik** [comment]
Unfortunately we currently don't have access to newer data. NCZI is migrating the system along with the jobs we originally designed for them. Once that is done we will hopefully be able to start publishing the data again (at least once in a while).

**Comment by mhudec** [comment]
@matejmisik - yes, I talked to NCZI in early August, they mentioned they are performing some kind of data migration (plus data source change) and that they expect to finish it in ~1 month time (so by end of August), but you were still pulling the data... well, looks like it moved to next phase then...

OK, thank you.
