### ISSUE TITLE
Pocet testov podla okresu

### ISSUE THREAD

**Issue by pomali** [Institut-Zdravotnych-Analyz/covid19-data#17]
Ku datam z okresu chyba nejaky dobry zdroj poctu vykonanych testov ako doplnenie `OpenData_Slovakia_Covid_PositiveTests_AgeGroup_District.xlsx`.

**Vedeli by ste doplnit pocet vykonanych testov?**

PS: Ku spominanemu datasetu `OpenData_Slovakia_Covid_PositiveTests_AgeGroup_District.xlsx` su tam uvadzani aj ludia s iba pozitivnym Ag testom?

**Comment by matejmisik** [comment]
Dobry den, pribudol novy dataset s PCR testami po okresoch (pozit aj negat). Nakolko to musi prechadzat dost komplexnym ETL procesom na strane NCZI budu rozdiely medzi pocatami reportovanymi v potvrdenych testoch. Publikujeme to primarne za ucelom pocitania a sledovania pozitivity po okresoch. https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/main/OpenData_Slovakia_Covid_PCRTests_District.csv
