### ISSUE TITLE
updaty pocas sviatkov

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#18]
ahojte chalani z IZA, mate nejako automatizovane updaty a budu updaty pocas sviatkov? alebo sa to robi manualne a teda otazka kedy mozeme ocakavat updaty pocas sviatkov?
P.S.: Stastne a vesele vianoce a SNR 2021 ;)

**Comment by matejmisik** [comment]
Servus, updates su sice automatizovane, len su dependent ci aj up stream sa
budu data pripravovat. Viem, ze umrtia nebudu (az po sviatkoch
kumulativne), ale verim ze zvysok bude. Treba to ale brat with a pinch of
salt, lebo sa bude velmi malo testovat, cize umelo bude situacia sa javit
ako zlepsujuca. Pekne sviatky prajeme, hlavne v zdravi

**Comment by MartinHBA** [comment]
thx
