### ISSUE TITLE
Očkovanie

### ISSUE THREAD

**Issue by sk-juroot** [Institut-Zdravotnych-Analyz/covid19-data#19]
Pozdravujem, v kontexte prechodu celej covid19 situácie do novej éry dostupnosti vakcíny by bolo super začať zberať údaje o zaočkovanej populácii. Samozrejme, najlepšie by bolo čo najdetailnejšie (okres, pohlavie, vek, a pod.), ale na začiatok budú dobré akékoľvek čísla naznačujúce aktuálny stav s očkovaním. Určite z nich budú môcť vzniknúť zaujímavé analýzy.

**Comment by matejmisik** [comment]
Agree, riesime to aby sme mali cim skor tie data strukturovane, idealne by som chcel aby sme ich mali rovnako ako testy na urovni jednotlivca s vekom, pohlavim, bydliskom (okres aspon), miestom ockovania, typ vakciny a poradie davky (uplne idealne aj povolanie, ale to asi nebude :) ). Len co sa toto nastavi zacneme to aj sem davat.

**Comment by sk-juroot** [comment]
Zdravím, je nejaký update k zverejneniu týchto dát? Vďaka.

**Comment by matuspavliscak** [comment]
@matejmisik Zdravím, chcel by som sa spýtať, aký je stav tejto inciatívy. Komunikujem s [ourworldindata](https://ourworldindata.org/) a oni by veľmi ocenili CSV s dátami o vakcinácií, aj základnými ako sú denné prírastky počtu zaočkovaných po dňoch. Aktuálne musia scrapovat [korona.gov.sk](https://korona.gov.sk/), kde po poslednom update zmizol dátum, ku ktorému to číslo sa vzťahuje. Ďakujem!
