### ISSUE TITLE
UPV vek

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#20]
mate k dispozicii aj data o veku pacientov na UPV? 
idealne dataset vo forme: AdmissionDate, Age, DischargeDate, Exitus(bool)

**Comment by KristianSufliarsky** [comment]
Ano mame, zistim ci by sme to mohli publikovat a dam vediet.

**Comment by MartinHBA** [comment]
ahojte, teraz to potrebujeme viac ako nikdy, nemuste presny vek, staci kohorty po 5 ako mate pri inych datasetoch, aby sme vedeli korektne preratat kolko je to na 100tis zaockovanych, nezaockovanych

**Comment by MartinHBA** [comment]
nuz ak sa to nepodarilo za vyse roka tak asi to je nad ludske sily 🥇
