### ISSUE TITLE
Nesprávne dáta Ag testov pre okresy

### ISSUE THREAD

**Issue by angelov-michael** [Institut-Zdravotnych-Analyz/covid19-data#23]
Neviem do akej miery siaha táto chyba, ale keď pozerám na Ag testy, tak pre okres Šaľa sa tam vyskytujú strašne nízke čísla, z vlastnej skúsenosti nerealistické. Okrem toho dáta zo Šale sú napr. 1.12.2020 a ďalšie až potom 14.12.2020 pričom sa jedná o jednotky ľudí. Odkiaľ vzniká tento problém a do akej miery zasahuje validitu dát?

https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/main/OpenData_Slovakia_Covid_AgTests_District.xlsx

**Comment by matejmisik** [comment]
V pripade niektorych prevadzkovatelov MOMAg dochadza k nespravnemu vykazovaniu lokacnych dat - kedy prevadzkovatel MOMAg, ktory prevadzkuje viacere MOMAg vykazuje pod jednou lokalitou. Toto s nimi aktivne riesi kordinacne centrum MZ a postupne by sa mali tieto anomalie odstranovat. Issue sa tyka konkretne Ag testov, nie PCR
