### ISSUE TITLE
zmeny kodovania

### ISSUE THREAD

**Issue by juniorUniv** [Institut-Zdravotnych-Analyz/covid19-data#24]
chlapi, dajte vediet v anoucemente, ze menite kodovanie z jedneho dna na druhy, vid dnesne z Win1250 na UTF-8, konkretne dnes v suboroch:
OpenData_Slovakia_Covid_PositiveTests_District.csv
OpenData_Slovakia_Covid_PositiveTests_AgeGroup_District.csv
atd ...
aj to patri ku dobrej praci

inak vdaka za aktualizacie

**Comment by juniorUniv** [comment]
tak sme uz naspat v 1250
tie exporty robite manualne? Ono sa to da aj strojovo, staci nastavit parametre.

**Comment by juniorUniv** [comment]
znovu
uz mi to pripomina ako napln prace - zmena encodingu v CSV, tak ako pride

**Comment by MartinHBA** [comment]
> znovu
> uz mi to pripomina ako napln prace - zmena encodingu v CSV, tak ako pride

ja som zmenil source na XLSX kde sa da, tam to drzi :)

**Comment by juniorUniv** [comment]
> > znovu
> > uz mi to pripomina ako napln prace - zmena encodingu v CSV, tak ako pride
> 
> ja som zmenil source na XLSX kde sa da, tam to drzi :)

ale to nie je cesta, ak ti hosi z IZA tvoria veci takto smerom von, tak ako vyzeraju smerom do vnutra? To je o zakladnych pravidlach chovania sa k datam, ktore vobec nedodrzuju.

Staci vytvorit jednu tabulku obec/okres/kraj s IDckami, ktore ma aj v DataCube ŠÚ (NUTS), aby sa dali prepajat dalsie celky. Jeden krat. A je vyrieseny problem, do vsetkych ostatnych tabuliek uz len IDcka. A nestane sa potom to, ze v jednej tabulke clovek najde v tom istom stlpci  "BratislavaII" a "Bratislava II". Toho bordelu najma s Bratislava a Košice je tam hojne. Nehovoriac o rychlosti Selectu cez Int vs String.

To su potom RAW agregaty? Alebo s takou Data quality narabaju vo svojom vyskume?
Ved sa pozrite na IT alebo Ireland, Florida data ... a mozem pokracovat dalej.

**Comment by KristianSufliarsky** [comment]
Dobry den,
Exporty su po novom nastavene tak, ze vsetko bude chodit von v UTF-8.
