### ISSUE TITLE
OpenData_Slovakia_Covid_Deaths_AgeGroup_District

### ISSUE THREAD

**Issue by ondrejHencz** [Institut-Zdravotnych-Analyz/covid19-data#25]
Dobrý deň. 
Ešte nie sú k dispozícii dáta do konca decembra?
Ďakujem

**Comment by MartinHBA** [comment]
momentalne v tomto datasete (OpenData_Slovakia_Covid_Deaths_AgeGroup_District.xlsx) chyba za 8.1.2021
za 9.1.2021 tam uz zas je

**Comment by ondrejHencz** [comment]
Dakujem

**Comment by ondrejHencz** [comment]
Dobrý deň
Len chcem upozorniť, že dva záznami sú tam s dátumom 8.1.2020. Myslím, že by tam malo byť 2021.
![image](https://user-images.githubusercontent.com/74894157/104772803-53484480-5774-11eb-976b-79966c1baca8.png)

**Comment by matejmisik** [comment]
Vdaka za upozornenie, opravene
