### ISSUE TITLE
OpenData_Slovakia_Covid_PositiveTests_AgeGroup_District.xlsx chyba 8.1.2021

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#26]
v datasete OpenData_Slovakia_Covid_PositiveTests_AgeGroup_District.xlsx chyba cely den 8.1.2021

**Comment by KristianSufliarsky** [comment]
Dakujem velmi pekne, data boli doplnene.
