### ISSUE TITLE
Plosne testovanie v okrese Nitra 9.-10.1.2021 a konzistencia AG testov vo Vasich datach

### ISSUE THREAD

**Issue by juniorUniv** [Institut-Zdravotnych-Analyz/covid19-data#28]
podla najvaciesho odbornika na Analyzy dat bolo v tomto Plosnom testovani vykonanych:
95 558 testov
Pocet pozitivnych spolu: 2 329
![image](https://user-images.githubusercontent.com/55238022/104432914-c9d51e80-5589-11eb-91f2-66635707c408.png)

avsak vo Vasom source: OpenData_Slovakia_Covid_AgTests_District.csv
mate toto:
![image](https://user-images.githubusercontent.com/55238022/104432758-9d210700-5589-11eb-8aea-556a01012595.png)

co je diametralne vzdialene od vysledkov menovanych hore

Znamena to:
- ze bude zase ina tabulka na vstupy k vysledkom?
- alebo to doplnite o niekolko dni neskor (uz preslo vela dni)?
- alebo treba hodit Vase data do skartovacky pretoze su absolutne nekonzistene?

Uvedomuje si v tomto state niekto, ze na zaklade zlych dat sa tazko da nieco riadit? Zodpovednost za take rozhodnutia?

**Comment by juniorUniv** [comment]
dnesna aktualizacia AG testov za okres NR:
![image](https://user-images.githubusercontent.com/55238022/104435403-a364b280-558c-11eb-923d-c1ebade6c373.png)

**Comment by KristianSufliarsky** [comment]
Dobry den,
Podla mna sa tieto data dostanu ku nam v najblizsich dnoch, je to na PZS ako tie data posielaju NCZI a nie je to nasim zavinenim, ze ich tam nedoplnaju. Ako som sa vyjadril uz v predchadzajucom issue, bolo by asi lepsie adresovat staznosti smerom na NCZI, ktore nam dodava data, ktore tu zverejnujeme.
