### ISSUE TITLE
novy jednoduchy dataset okresy

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#3]
ak by sa dalo jednoducho pridat novy dataset csv ako je tento na cele SK:
https://mapa.covid.chat/export/csv
ale spravit to na okresy (prip. aspon kraje) , to by nemal byt velky problem. vdaka vopred!

**Comment by Xubor** [comment]
Takýto dataset tiež na covid.chat existuje: [https://mapa.covid.chat/map_data/daily](https://mapa.covid.chat/map_data/daily)
Ja to napr. používam v tomto projekte: [https://covid-trendy-sk.github.io/](https://covid-trendy-sk.github.io/)

Ale je to také neoficiálne, posledný deň-dva sú častokrát nesprávne údaje a mešká to vždy aspoň jeden deň za NCZI zverejnenými údajmi.

Čiže sa taktiež prihováram za normálny dataset po okresoch zverejnený tu.

**Comment by MartinHBA** [comment]
@Xubor vdaka, zvlast pre mna hodnotny udaj by bol pocet testov, co je momentalne udaj len na urovni celeho SK

**Comment by matejmisik** [comment]
Takto nejak? https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/main/OpenData_Slovakia_Covid_PositiveTests_District.csv
