### ISSUE TITLE
AG dataset

### ISSUE THREAD

**Issue by davidkrck** [Institut-Zdravotnych-Analyz/covid19-data#30]
Dobrý deň,

chcel by som som sa spýtať, ako funguje zverejňovanie datasetu Antigénových testov. Všimol som si, že k dennej aktualizácie týchto dát prichádza okolo poobedných hodinách a vždy je najnovší deň nových testov, deň aktualizácie.

Je to iba o deň posunuté alebo ide už aj o dáta z dňa aktualizácie?

Ďakujem

**Comment by matejmisik** [comment]
Dobry den, Ag MOM priebezne hlasia data do systemu, niektore ale v batches napr v noci. NCZI ma cutoff time (neviem presne kedy) kedy data spracuje a nahrava ich do shared location odkial ich my spracujeme. Ag MOM niekedy vykazuje aj spatne, preto tieto data sa mozu menit aj za predoslych niekolko dni. Kazdopadne datum by mal reflektovat datum vykonania testu.
