### ISSUE TITLE
earlier dates for file OpenData_Slovakia_Covid_PositiveTests_AgeGroup_District ?

### ISSUE THREAD

**Issue by timriffe** [Institut-Zdravotnych-Analyz/covid19-data#32]
Hi again,
Thanks for this data! I'd like to transform this file into a cumulative time series by age, sex, and region. However, the earliest date given is in September, 2020. To do this, one either needs the same time series starting from early 2020, or else a snapshot of the cumulative (over time) age-sex distribution by regions sometime since last September. Has the earlier part of this file been removed for size reasons? Is there another way to obtain it?
Many thanks for any guidance,

**Comment by matejmisik** [comment]
Hi Tim, unfortunately we have access to this granularity only as of September & as the institution responsible for the data is extremely overloaded we haven't been requesting earlier statistics. Once the vaccination program gets under way & NCZI has a bit more time we will try to reconstruct the history.
