### ISSUE TITLE
sprehladnenie

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#33]
neuvazujete to trosku sprehladnit do foldrov? napr. : Testing, Hospitals, Vaccination, Deaths, Automat
vdaka za data

**Comment by KristianSufliarsky** [comment]
Dobrý deň,

Áno uvažujeme, a v prípade že to budeme tak budeme duplicitne pár dní uploadovať do nových súborov, kým sa každý pripraví na tieto zmeny povôdné dáta z hlavnej vetvy odstránime.
