### ISSUE TITLE
Umrtia - dáta

### ISSUE THREAD

**Issue by Maros68** [Institut-Zdravotnych-Analyz/covid19-data#34]
Súbor s úmrtiami podľa veku a Okresu obsahuje len 2969 záznamov , v súčastnosti je v oficiálnych štatistikách uvádzaných 3801 umrti.. viete to aktualizovať ak aby to zodpovedalo s oficiálnymi informáciami..

**Comment by richienko** [comment]
bump

**Comment by freedomlives** [comment]
Does the Date in this data mean the date the person died, or the date when their death was reported by ÚDZS? Would be interesting to know, now that Datacube has deaths by week and vekove skupina for all of 2020.

**Comment by matejmisik** [comment]
Sorry folks, my bad - the deaths data take quite a bit of manual processing and cleaning so I don't get around to it often. I am discussing with Dr. Palkovic how to automate the process & the guys at Slovensko Digital already said they are willing to help create an automation flow for Dr Palkovic (waiting now for him to give us a specification of the process and what he needs). I'll try to increase the upload interval to at least once every two weeks. Good news is I now have more detailed data on deaths "with" covid, so once I have these cleaned I will post them as well.

**Comment by matejmisik** [comment]
@freedomlives the date in the detailed excel contains date of death. In the aggregated its on a reporting basis, so the two don't overlap.

**Comment by freedomlives** [comment]
@matejmisik Dakujem!
