### ISSUE TITLE
Údaje za víkendové AG testovanie sú nekompletné.

### ISSUE THREAD

**Issue by kikonan** [Institut-Zdravotnych-Analyz/covid19-data#39]
Za víkend je tam asi 0,56M testov, pritom len za sobotu bolo reportovaných 1,3M. Takže do úplných dát chýba ešte veľmi veľa.

**Comment by KristianSufliarsky** [comment]
Dobrý deň,
V popise dát, ktorý viete napríklad nájsť [tu](https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/main/README.md), sú vysvetlené dôvody prečo tie dáta chýbajú.

**Comment by kikonan** [comment]
Predpokladám, že už dáta máte kompletné keďže ich predseda vlády pred chvíľou prezentoval. Kedy ich tu uvidíme?

**Comment by MartinHBA** [comment]
> Predpokladám, že už dáta máte kompletné keďže ich predseda vlády pred chvíľou prezentoval. Kedy ich tu uvidíme?

https://github.com/MartinHBA/VedaPomahaData/blob/main/data/ScreeningDataUradVlady.csv

**Comment by kikonan** [comment]
> > Predpokladám, že už dáta máte kompletné keďže ich predseda vlády pred chvíľou prezentoval. Kedy ich tu uvidíme?
> 
> https://github.com/MartinHBA/VedaPomahaData/blob/main/data/ScreeningDataUradVlady.csv

Na tlačovkách vlády už boli prezentované dvoje ďalšie výsledky (na githube nezverejnené), dáta IZA stále nie sú za víkend 23. -24.1. kompletné. Kedy sa vám tie čísla stretnú?
