### ISSUE TITLE
data refresh

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#4]
dalo by sa relevantne data sety nastavit raz denne refresh do githubu please?

**Comment by matejmisik** [comment]
Snazime sa pravidelne, avsak najprv to prebieha procesingom u nas, kedze sa data zlievaju z roznych stran v roznych formatoch... Cielovo by vsetko co mame tu malo byt v NCZI API, avsak tam su tiez teraz extremne kapacitne vytazeni a robia na urgent veciach a zial potom ostava malo casu na pekne opendata :/ Slowly getting there!
