### ISSUE TITLE
Nesprávne čísla v Hospital_Details.csv

### ISSUE THREAD

**Issue by example-sk** [Institut-Zdravotnych-Analyz/covid19-data#40]
V súbore OpenData_Slovakia_Covid_Hospital_Details.csv sa nachádzajú čísla ako 522727272727273, 416666666666667, 133333333333333. Možno nesprávne miešanie dátových typov niekde na pozadí?

**Comment by KristianSufliarsky** [comment]
Dobrý deň,
Asi nastal problém s desatinnou čiarkou, my používame "," namiesto ".". Skúste to prosím skontrolovať a dajte mi vedieť. 
Vďaka

**Comment by example-sk** [comment]
Ďakujem, máte pravdu. Prehliadol som desatinné čiarky.

**Comment by KristianSufliarsky** [comment]
Vďaka za spätnú väzbu.
