### ISSUE TITLE
OpenData_Slovakia_Covid_Hospital_Details.csv

### ISSUE THREAD

**Issue by ondrejHencz** [Institut-Zdravotnych-Analyz/covid19-data#52]
Dobrý deň
1. Všimol som si, že 9.2.2021; Nitra; Fakultná nemocnica nemá vyplnené dáta. a tak isto sú tam záznamy NA ktoré začali pribúdať od 18.1.2021. 
2. Chcel by som sa spýtať, či je možné rozdeliť aj vyliečených podľa vzoru PositiveTests_AgeGroup_District?
3. Existujú záznamy ohľadne vyliečených z AG testov, alebo pozitívny odbúdajú (vyliečili sa) podľa počtov spred 10 dní? Dá sa to zistiť prosím?

Ďakujem za odpoveď.

**Comment by KristianSufliarsky** [comment]
Dobrý deň,

Kontroloval som tu chybu, ale vyzerá že by už mala byť opravená, môže sa totiž stať, že nemocnica nestihne vykázať aktuálny stav pred tým ako nám prídu dáta z NCZI, čo sa môže následne objaviť v nami publikovaných súboroch. 
Čo sa týka počtu vyliečených pacientov, tak ÚVZ tieto informácie má, ale NCZI dodáva iba počty vyliečených za predchádzajúci deň (AG+PCR dokopy). 
Čo sa týka vyliečenia nie je to vraj tak triviálne, že automaticky po 10 dňoch je pacient evidovaný ako vyliečený, no záleží to na tom či je už asymptomatický, alebo nie. Toto ale všetko spracováva ÚVZ.

Dúfam že som zodpovedal všetky Vaše otázky.

**Comment by ondrejHencz** [comment]
Dobrý deň. Áno zodpovedali. A dá sa ich požiadať o dodanie takýchto dát? Myslím vyliečených podľa veku a regiónu. 
Ďakujem

**Comment by KristianSufliarsky** [comment]
Dobrý deň,
Je teraz našou snahou zabezpečiť, aby to dodávali NCZI, ale ak ste to mysleli tak či ich nedodajú osobne Vám, tak by som povedal že asi nie.

**Comment by ondrejHencz** [comment]
Nie. Myslel som Vám... Ďakujem za ochotu

**Comment by ondrejHencz** [comment]
Ďakujem
