### ISSUE TITLE
Methodology behind recovered patients statistics

### ISSUE THREAD

**Issue by daniel-pl** [Institut-Zdravotnych-Analyz/covid19-data#53]
Could you provide some information or references on the methodology behind the number of recovered patients statistics? 
I was not able to find any details on this from http://www.nczisk.sk, which seems to be the source of the data.

**Comment by kajbo92** [comment]
why you changed previous datasets?

**Comment by KristianSufliarsky** [comment]
Hello, 
The number of recovered patients is provided by the Public health authority on a daily basis and it consists of recovered patients diagnosed either with PCR test or antigen test. If a patient does not suffer from any syptoms within 10 days after his/her positive test, he/she is classified as recovered on 10th day. In case of on-going symptoms, he contacts the Regional public health authority and then they further track the development of his/her disease.

**Comment by kajbo92** [comment]
@KristianSufliarsky Hi Kristian, is possible get daily updated data with Active cases, recovered stats, vaccination etc? Previously i was able reach csv or json file from korona.gov but dataset was changed and now is without this stats, thanks for info

**Comment by daniel-pl** [comment]
Thanks @KristianSufliarsky, that clarifies it!
