### ISSUE TITLE
Pocty vyliecenych v DailyStats

### ISSUE THREAD

**Issue by diavollo** [Institut-Zdravotnych-Analyz/covid19-data#55]
Pri premenovani a pridavani stlpcov v DailyStats, zmizol stlpec "Pocty vyliecenych". Umysel, alebo chyba? Inde som to nenasiel...

**Comment by KristianSufliarsky** [comment]
Dobrý deň,
ako som písal tu, https://github.com/Institut-Zdravotnych-Analyz/covid19-data/issues/56 stĺpce boli odstránené kvôli chybe ktorú obsahovali.
Ďakujem za porozumenie.
