### ISSUE TITLE
OpenData_Slovakia_Covid_DailyStats

### ISSUE THREAD

**Issue by ondrejHencz** [Institut-Zdravotnych-Analyz/covid19-data#56]
Dobrý deň
Predtým sa do tejto tabulky dávalo 8 stĺpcov a odrazu ich je len 6. chýba tam počet vyliečených a počet aktívnych.
Dá sa to uvádzať opäť?
Ďakujem.

**Comment by KristianSufliarsky** [comment]
Dobrý deň,
Tento dataset som tvoril z toho ktorý bol dostupný na stránke korona.gov, a tam boli teraz tieto stĺpce odstránené. Čiže kým sa nevyriešia chyby ktoré tam boli, bude zatiaľ aj tento dataset vyzerať takto. 
Ďakujem veľmi pekne za pochopenie.

**Comment by ondrejHencz** [comment]
Ďakujem za odpoveď.
