### ISSUE TITLE
Updates to OpenData_Slovakia_Covid_Deaths_AgeGroup_District.csv ?

### ISSUE THREAD

**Issue by freedomlives** [Institut-Zdravotnych-Analyz/covid19-data#58]
Since I see that there were deaths on the 25. December listed here, but none reported on that day, is correct to understand that this file lists the actual date of each death, rather than date of report?

Will there be an update to this data?

Also, in the aggregate data that is being kept up to date, why aren't deaths "with" COVID being included, as they were in the aggregate file OpenData_Slovakia_Covid_DeathsCumulative.csv?

**Comment by freedomlives** [comment]
Actually, I've gone ahead and manually updated the latter file with the data from https://covid-19.nczisk.sk/sk
I'll make a pull request of it in a moment

**Comment by matejmisik** [comment]
Sorry folks, my bad - the deaths data take quite a bit of manual processing and cleaning so I don't get around to it often. I am discussing with Dr. Palkovic how to automate the process & the guys at Slovensko Digital already said they are willing to help create an automation flow for Dr Palkovic (waiting now for him to give us a specification of the process and what he needs). I'll try to increase the upload interval to at least once every two weeks. Good news is I now have more detailed data on deaths "with" covid, so once I have these cleaned I will post them as well.
