### ISSUE TITLE
Ct values pre PCR dataset

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#60]
Vraj sa rutinne robia pri RT PCR aj Ct values hodnoty. Dalo by sa pridat prosim ako stlpec pre PCR dataset district_age_gender?

**Comment by MartinHBA** [comment]
Toto sa planuje, mame čakať ci nebude to?

**Comment by Tibor17** [comment]
Zaujima ma ako daleko ste sa dostali s CT parametrom.
Najskor 40 - 60, potom WHO prehralo sud s Robertom Kenedym mladsim, a teraz WHO hovori ze PCR musi byt kombinovane s klinickym vysetrenim.
Mate dnes CT na urovni 25 alebo 26? Alebo este stale klamete?
Viete o tom ze judr. Peter Weise dal podanie na Haagsky sud pretoze tento covid podvod je prave postaveny na manipulacii s cislami CT parametru v testsetoch.
Potom sa Vam ozvem ked Mikas bude predvedeny, hoci asi Caputova a Nad sa na Haagsky sud dostane prioritne. No bohu zial, Mikas este nie je tak vysoko postaveny, ale aj to bude ale na sude!

**Comment by MartinHBA** [comment]
zatvaram stary leziacik
