### ISSUE TITLE
Daily status

### ISSUE THREAD

**Issue by ondrejHencz** [Institut-Zdravotnych-Analyz/covid19-data#62]
Dobrý deň páni
Chcel by som upozorniť na denný status. Včera sme mali 278 tisíc poz. a dnes je ich 514 tisic? Aj korona gov udava 279 tisic dnešnému dňu. Mohli by ste to skontrolovať?
Ďakujem
![PCR_pozitivnych_01](https://user-images.githubusercontent.com/74894157/108113101-55fdc880-7097-11eb-9965-19624f726b66.png)
![PCR_pozitivnych_02](https://user-images.githubusercontent.com/74894157/108113103-56965f00-7097-11eb-86aa-48ee52e9e11f.png)

**Comment by ondrejHencz** [comment]
Dobrý deň
Ešte by som pridal jednu prosbu. oficiálne číslo na korona gov je 279 696, ale keď sčítam pozitívnych podľa regionu alebo aj podľa veku tak výsledok je nižší 274 342. Vedeli by ste to preveriť? Ďakujem
![OpenData_Slovakia_Covid_PositiveTests_AgeGroup_District_2021_02_16](https://user-images.githubusercontent.com/74894157/108129273-42119100-70ae-11eb-8e3c-db22850b56cb.png)
![OpenData_Slovakia_Covid_PositiveTests_District_2021_02_16](https://user-images.githubusercontent.com/74894157/108129275-42aa2780-70ae-11eb-80ff-0f8cfaab928e.png)

**Comment by kajbo92** [comment]
vyzera to tak, ze spojili PCR + AG

**Comment by mkaj35** [comment]
tak toto je naozaj dátové peklo. Od 3/Sep sa počet fiktívnych "Pocet.potvrdenych.PCR.testami" ráta ako počet naozajstných "Pocet.potvrdenych.PCR.testami[predch.den]" + fiktívne "Dennych.PCR.prirastkov". To si to fakt nikto nedokáže skontrolovať predtým, ako to postne na verejnosť ???

**Comment by mkaj35** [comment]
OK, už je to fixnuté

**Comment by ondrejHencz** [comment]
Dobrý deň
Áno jedna časť otázky je vyčistená. Super. 
Ešte súčet pozotívnych ostáva otvorený. Ináč v tých tabuľkách som nemal žiadne vzorce. to sú len surové dáta. vzorce mám v inom zošite. 
Ďakujem

**Comment by ondrejHencz** [comment]
Dobrý deň
Podrobnejšia štatistika sa začala robiť až v septembry, preto chýbajú dáta (viď prílohu)? Ak áno, tak dal by sa skontrolovať deň 29.1.2021 kde je vykázaných 991 z 2182 potvrdených?
Ďakujem

[porovnanie_potvrdenych.xlsx](https://github.com/Institut-Zdravotnych-Analyz/covid19-data/files/6005480/porovnanie_potvrdenych.xlsx)
