### ISSUE TITLE
Completeness of OpenData_Slovakia_Covid_Deaths_AgeGroup_District.csv for 2020?

### ISSUE THREAD

**Issue by freedomlives** [Institut-Zdravotnych-Analyz/covid19-data#63]
Thanks for updating this data!

Is there any estimate of how complete this data is for 2020? 

The first version, till Jan 18th, had a total of 2357 deaths in 2020, the updated version increased to 2688 during 2020

Are the deaths per day including both those who died "with" and "from" COVID, or just those who died "from" COVID?

Right before the end of the year, from 31.12.2020 till 07.01.2021, the number of deaths per day plummets. Which seems really weird. Is it reasonable to expect that pathologists are still investigating some deaths from 2020 / early 2021 and the numbers on these dates will rise as data is updated?

![deaths_day_from_sep](https://user-images.githubusercontent.com/16663872/108335000-c9582500-71d2-11eb-84e8-3b79c089e6e1.png)
.

**Comment by matejmisik** [comment]
Just added these with the recent update. We where missing this data as it never arrived to us during the holidays, got my hands on them and the file should now contain all recorded deaths due to covid.
