### ISSUE TITLE
Aktualizácia a zdroj

### ISSUE THREAD

**Issue by kajbo92** [Institut-Zdravotnych-Analyz/covid19-data#67]
Zdravím, je nejaký konkrétny čas, kedy sa aktualizujú daily stats, vaccines, popr. je niekde dostupný zdroj, ktorý sa aktualizuje v čase ako na webe nczi? Ďakujem za info

**Comment by KristianSufliarsky** [comment]
Dobrý deň,
Ospravedlňujem sa za ten čas kým som sa k tomuto dostal. Áno u nás máme nastavené že aktualizačný skript by mal začať bežať o 9:58, a následne podľa objemu dodaných dát zbehne. Každopádne záleží na NCZI, kedy nám dáta dodá, ale v poslednej dobe to býva do 10.
