### ISSUE TITLE
Data request: PCR negative tests with age, gender, date, region

### ISSUE THREAD

**Issue by tista3** [Institut-Zdravotnych-Analyz/covid19-data#68]
Bolo by mozne vypublikovat aj data o negativnych vysledkoch PCR testov?
Take iste ako tu, ale aj so zaznamami o negativnom vysledku.
https://github.com/Institut-Zdravotnych-Analyz/covid19-data/blob/main/PCR_Tests/OpenData_Slovakia_Covid_PositiveTests_AgeGroup_District.xlsx

**Comment by KristianSufliarsky** [comment]
Dobrý deň,
mrzí ma to ale takéto informácia o pacientoch s negatívnym výsledkom nemáme. Taktiež sa ospravedlňujem, že mi to trvalo tak dlho odpísať.
