### ISSUE TITLE
Deaths not updated 11 days

### ISSUE THREAD

**Issue by tista3** [Institut-Zdravotnych-Analyz/covid19-data#72]
Data in Deaths are 11 days old. What is the update frequency?

**Comment by freedomlives** [comment]
There doesn't seem to be a set frequency when that data gets updated. You can manually add to the data on deaths reported each day by going to https://covid-19.nczisk.sk/sk and looking at the detailed view of deaths (you'll need to do this on a desktop or with desktop mode enabled on the phone browser).

**Comment by MartinHBA** [comment]
@freedomlives , well... That's shame...

**Comment by freedomlives** [comment]
@tista3 I've updated it, see here: https://github.com/freedomlives/SK_C19_updates
That is only deaths reported by date. We'll have to wait for IZA to update the other dataset, which has the date the death occurred. It seems that in January there was a backlog of deaths for the pathologists to examine, as the number of reported deaths by date increased in December when that data was updated.

**Comment by freedomlives** [comment]
@MartinHBA I don't get the impression, shall we say, that the Slovak government agencies have been exactly excited to get information on deaths out. Except for the seriousness of it, it was funny to see how no-one had a clue that there was detailed data here and on the portal above, until like last week, when that page "data bez patosy" finally started reporting deaths "from" and "with" COVID19, which seems like what most other countries do.
Maybe, given enough time, they'll also see how the recommendation on "social distance" of the Slovak government goes against WHO, ECDC and what has apparently been working in the countries with lower mortality.

**Comment by freedomlives** [comment]
@matejmisik is there not new data by now?

**Comment by KristianSufliarsky** [comment]
Hi @freedomlives,
as I mentioned [here](https://github.com/Institut-Zdravotnych-Analyz/covid19-data/issues/73), we will be probably updating this dataset daily.
If you have any more questions, do not hesitate to contact me.

**Comment by matejmisik** [comment]
Sorry folks, my bad - the deaths data take quite a bit of manual processing and cleaning so I don't get around to it often. I am discussing with Dr. Palkovic how to automate the process & the guys at Slovensko Digital already said they are willing to help create an automation flow for Dr Palkovic (waiting now for him to give us a specification of the process and what he needs). I'll try to increase the upload interval to at least once every two weeks. Good news is I now have more detailed data on deaths "with" covid, so once I have these cleaned I will post them as well.
