### ISSUE TITLE
Deaths 

### ISSUE THREAD

**Issue by freedomlives** [Institut-Zdravotnych-Analyz/covid19-data#79]
@matejmisik OpenData_Slovakia_Covid_Deaths_AgeGroup_District is still just "umrti na COVID" or also "s COVID"?

**Comment by matejmisik** [comment]
Still just primary cause of death covid. Planning to add "with" covid, however I need to further clean the data. Once we add also "with" covid we will add a flag indicating primary vs. secondary cause.
