### ISSUE TITLE
API data access a viac

### ISSUE THREAD

**Issue by radoondas** [Institut-Zdravotnych-Analyz/covid19-data#8]
Dobry den,
v prvom rade som nesmierne stastny ze vznika iniciativa na verejne dostupne a strohjovo citatelne data. Dakujem.

Vo svojom volnom case, ako dennu rutinu, od zaciatku pandemie zbieram [data](https://github.com/radoondas/covid-19-slovakia) i ja kedze neboli a stale nie su rozumne pristupne. Zaroven som vytvoril [blog post](https://radoondas.io/posts/2020/visualise-covid-19-using-elastic-stack/) a jednoduchy [dashboar](https://covid-19.radoondas.io/) o ktorom som hovoril aj na verejnom [meetupe](https://youtu.be/eP-mn2vYBLo) s pouzitim kokretnej technologie.

Rad by som privital okrem dennych aktualizovanych (strohjovo citatelnych) dat, aj API ktore by bolo pristupne na dalsie jednoduche spracovanie. 
Lepsia granularita dat by sa iste hodila mnohym analytikom na vytvaranie zaujimavych vizualizacii, analyz a vzdelevanie.
Obce, Muzi vs zeny, pripadne vek. 

Rad sa podelim o skusenosti, radosti a bole analyzy dat. 

Vdaka!

**Comment by St1c** [comment]
Tiez sa pripajam k nazoru nadomnou. Aj keby neexistovalo nejake jednoduche API, uz aj to, keby boli vsetky informacie pravidelne commitovane sem na github - v nejakej unifikovanej podobe - aj to by bol velky krok vpred. API uz si snad vie vytvorit kazdy aj sam v zavislosti na technologii ktoru potrebuje. No ja uz napriklad dlhsie pozeram kedy sa zacnu publikovat aj data z AG testov a uz ked sa konecne zacali - tak su oneskorene o 4 dni. CSV je akceptovatelne - ale uz ked je to tu na GitHube - mohol by by aspon vo forme, ktoru vie GH korektne zobrazit.

**Comment by juniorUniv** [comment]
suhlas api si vie urobit kazdy sam. dostatok sirokospektralnych dat je vacsi problem.
re dashboardy:
problemom kazdeho takeho dashboardu je jeho vypovedna hodnota. priklad:
1. k comu mi je vidiet zafarbeny okres podla poctu Positive cases, ked tam nemam pohlad/filtraciu cez populaciu v okrese, hustotu obyvatelstva, dynamiku narastu v case, ... ? Snad okres s 300 Positive cases a 20tis obyvatelmi je na tom rovnako ako okres s 300 Positive cases a 10tis obyvatelmi?
2. k comu mi je vidiet pohlad na pocet Positive cases v SR? Potrebujem predsa distribuciu na najnizsiu moznu sregionalnu jednotku.
3. k comu mi je graf zobrazujuci pocet testov? Ked neviem, kolke z nich boli vykonane poziadavkou o test z organizacie (zamestnavatel, hotel, ...), kolke z nich z titulu stretu s pozitivne indikovanou osobou (zbiera sa casovy usek stretu), kolke z nich boli kedy nahlasene a kedy vykonane, miesto testu vs trvale bydlisko, symptomaticke data, ...
4. a takto sa da pokracovat v celej logike dashboardov, ktore su pekne vizualne, ale zial len pekne
5. len pekny dashboard nie je analyza dat.

**Comment by MartinHBA** [comment]
> CSV je akceptovatelne - ale uz ked je to tu na GitHube - mohol by by aspon vo forme, ktoru vie GH korektne zobrazit.
problem je v SK exceli z ktoreho je to ulozene, SK excel pouziva "," ako oddelovac desatinnych miest a potom CSV exportuje ako ";" delimited. To by sa dalo fixnut velmi jednoducho, data by mali obchadzat XLSX a mali by byt zo zdroja strojovo dumpovane do csv. Technologii ktore to dokazu je na trhu viac nez dost.

**Comment by matejmisik** [comment]
Check it out, tim z Slovensko.Help pripravuju API na tieto github data, ktore tu publikujeme. https://data.korona.gov.sk/ (postupne sa bude rozsirovat)

**Comment by radoondas** [comment]
Dakujem! Vyzera to slubne.
