### ISSUE TITLE
Covid automat CSV a XLS starsie datumy

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#81]
dalo by sa prosim namiesto replace robit append dat? alebo aspon spravit novy subor covid automat historical a tam davat vsetky aj minule hodnoty covid automatu v jednom subore, vdaka

**Comment by diavollo** [comment]
append by bol asi nezmysel, kedze pravidla covid automatu sa menia a meni sa pritom nielen pocet stlpcov, ale aj ich pomenovanie a obsah...
historical by asi mohli, ak tie udaje este niekde maju.... zrejme ano. Manualne si ho mozes poskladat ak prejdes rozne **Fork**y. Nezabudni, ze kazdy subor vo forku ma aj svoj diff... Vela stastia

**Comment by MartinHBA** [comment]
Closing
