### ISSUE TITLE
AgTests- februar 2021

### ISSUE THREAD

**Issue by diavollo** [Institut-Zdravotnych-Analyz/covid19-data#82]
Minimalne v OpenData_Slovakia_Covid_AgTests_District sa vam stratili data za cely februar 2021 :(
co dodat?

**Comment by diavollo** [comment]
Vypadok dat pokracuje aj dnes. Okrem uz zmieneneho adresara **AgTests** su postihnute aj subory v **DailyStats**

**Comment by KristianSufliarsky** [comment]
Uz by to malo byt opravene,
