### ISSUE TITLE
AgTests január 2021 - duplicita údajov

### ISSUE THREAD

**Issue by jancsi70** [Institut-Zdravotnych-Analyz/covid19-data#83]
Od 10.4.2021 údaje za január 2021 v súboroch OpenData_Slovakia_Covid_AgTests_District sú dvojnásobné.

**Comment by KristianSufliarsky** [comment]
Dobrý deň,
Veľmi pekne ďakujem za upozornenie, dáta by už mali byť opravené.
S pozdravom
Šufliarsky
