### ISSUE TITLE
Data z cakarne

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#86]
vedeli by ste dat data z cakarne kazdy den ako sa to tam hybe priebezne?
![image](https://user-images.githubusercontent.com/49184077/115557417-fba90000-a2b1-11eb-9f7e-7db40af0d65e.png)

**Comment by matejmisik** [comment]
Dobry den, toto je nasim cielom dostat tieto data "von", cielovo buduci tyzden by sme mali mat konecne spristupnene na dennej baze data zaockovanych po vekovkach a pohlavi. Nasledne taktiez cakaren (kolko ludi caka po veku, okresoch, ci cakaju s terminom alebo bez...)
