### ISSUE TITLE
COVID automat - hodnotenie okresov

### ISSUE THREAD

**Issue by kikonan** [Institut-Zdravotnych-Analyz/covid19-data#87]
Všetky okresy postupne prechádzajú do lepších farieb COVID automatu, iba BA a KE sú vždy v závese, hoci všetky ostatné parametre sú porovnateľné.  Porovnajte si napr NZ a BA - vážená incidencia je takmer zhodná. Zmena incidencie je v prospech BA. Hospitalziácií je v BA viac, ale pri násobne vyššom počte obyvateľov... Nie je chyba vo vyhodnocovaní hospitalizácií? Zohľadňuje sa prepočet na počet obyvateľov?

**Comment by kikonan** [comment]
Ešte mi napadá, či nie je problém s tým, že BA a KE majú samostatné riadky pre okresy, ale niektoré údaje sú za celé mesto...

**Comment by matejmisik** [comment]
Dobry den, trend je v pripade KE aj BA pozitivny, cize pri vyhodnoteni buduci tyzden uz budu asi obe ruzove. Do toho hodnotenia vstupuju okre vazenej incidencie aj trend, hospitalizacie (na 100.000 obyvatelov, s tym, ze sa priraduju k okresom podla bydliska, nie podla nemocnice, cize nemali by byt znevyhodnene okresy s nemocnicami) a finalne aj zhodnotenie regionalneho hygienika / hygienicky. 

Spravne hovorite, ze BA a KE sa posudzuju kumulativne na urovni celeho mesta, napriek tomu ze pozostavaju z viacerych okresov. V tabulke su tieto okresy separe cisto z dovodu vizualizacie na mape. 

Kazdopadne, verim, ze sa cim skor prijme update covid automat, kde sa modifikuju viacere tieto parametre, aby to bolo citatelnejsie a predvidatelnejsie (napr zrusenie vazenej incidencie, ci vylucenie hospitalizacii na regionalnej urovni).

**Comment by kikonan** [comment]
Ďakujem za rýchlu reakciu. Stiahol som si aktuálny XLS pred chvíľou (tesne po aktualizácii) a tam bola BA ešte uvedená ako Stab (preto som sa ozval), takže prechod zatiaľ asi nehrozí...
