### ISSUE TITLE
diakritika nazvy okresov v PCR datasete

### ISSUE THREAD

**Issue by MartinHBA** [Institut-Zdravotnych-Analyz/covid19-data#88]
PCR dataset od dnes rana problemy s diakritikou
OpenData_Slovakia_Covid_PositiveTests_AgeGroup_District.xlsx
![image](https://user-images.githubusercontent.com/49184077/116523490-93bc7000-a8d6-11eb-9349-b87b111bf1a7.png)

**Comment by KristianSufliarsky** [comment]
Dobrý deň,
Už by to malo byť opravené.
