### ISSUE TITLE
Narodny automat od 3.5.2021

### ISSUE THREAD

**Issue by mariasimalova** [Institut-Zdravotnych-Analyz/covid19-data#89]
OpenData_Slovakia_CovidAutomat.csv aj xlsx su chybne, kedze od 3.5. bude platit narodny automat. Hodnota covid_automat by mala byt najmenej 5, ale vo vasich datach sa vyskytuju aj 4-ky.

**Comment by MartinHBA** [comment]
@mariasimalova , asi mozes zavriet ako neaktualne
